/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/missions` | `/missions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `/mission/[id]/create`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/mission/[id]/delete`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/mission/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/mission/[id]/modify`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/missions` | `/missions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownOutputParams; } | { pathname: `/mission/[id]/create`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/mission/[id]/delete`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/mission/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/mission/[id]/modify`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/missions${`?${string}` | `#${string}` | ''}` | `/missions${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profil${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/missions` | `/missions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | `/mission/${Router.SingleRoutePart<T>}/create${`?${string}` | `#${string}` | ''}` | `/mission/${Router.SingleRoutePart<T>}/delete${`?${string}` | `#${string}` | ''}` | `/mission/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/mission/${Router.SingleRoutePart<T>}/modify${`?${string}` | `#${string}` | ''}` | { pathname: `/mission/[id]/create`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/mission/[id]/delete`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/mission/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/mission/[id]/modify`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
